apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 8081
      targetPort: 8081
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: vijaykumardaha/user-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SECRET
              value: "fftrack"
            - name: PORT
              value: "8081"
            - name: HOST
              value: "localhost"
            - name: DATABASE
              value: "mongodb://mongo:27017/user"
          imagePullPolicy: Always